FROM nginx:alpine

# 2. Copier vos fichiers web locaux (par exemple depuis un dossier "app" ou "html") dans le dossier public de Nginx
COPY ./app /usr/share/nginx/html

# 3. Exposer le port 80 pour le trafic web
EXPOSE 80